/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package krishna_laundry;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thakur-huni
 */
public class AllOrders extends javax.swing.JFrame {

    /**
     * Creates new form AllOrders
     */
    AdminHome adminHome;
    public AllOrders(AdminHome obj) {
        initComponents();
        this.adminHome=obj;
        fetchOrders();
    }
     void fetchOrders()
    {
        try
            {
                ConnectDB connectDB=new ConnectDB();
                Connection con=(Connection) connectDB.connect();
                 PreparedStatement  ps= con.prepareStatement("SELECT * FROM orders order by date desc");
                 ResultSet rs=ps.executeQuery();
                 DefaultTableModel model = new DefaultTableModel();
                 model=(DefaultTableModel)tableOrder.getModel();
                    model.setRowCount(0);
                   
                    while (rs.next()) {
                        Object o[] = {rs.getInt(1), rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10)};
                        model.addRow(o);
                    }
                 
                  connectDB.disconnect();
            }
            catch(Exception e)
            {
                System.out.println("Error AllOrders.java : "+e);

            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOrder = new javax.swing.JTable();
        lblFetchSts = new javax.swing.JLabel();
        lblUpdateSts = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("All Orders");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel1.setText("All Orders");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/back.png"))); // NOI18N
        btnBack.setAlignmentX(0.3F);
        btnBack.setAlignmentY(5.5F);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Shirt", "T-Shirt", "Pant", "Towel", "Pajama", "BedSheet", "Date", "Status", "Username"
            }
        ));
        tableOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableOrderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableOrder);
        if (tableOrder.getColumnModel().getColumnCount() > 0) {
            tableOrder.getColumnModel().getColumn(0).setMinWidth(70);
            tableOrder.getColumnModel().getColumn(0).setPreferredWidth(70);
            tableOrder.getColumnModel().getColumn(0).setMaxWidth(70);
            tableOrder.getColumnModel().getColumn(1).setMinWidth(50);
            tableOrder.getColumnModel().getColumn(1).setPreferredWidth(50);
            tableOrder.getColumnModel().getColumn(1).setMaxWidth(50);
            tableOrder.getColumnModel().getColumn(2).setMinWidth(70);
            tableOrder.getColumnModel().getColumn(2).setPreferredWidth(70);
            tableOrder.getColumnModel().getColumn(2).setMaxWidth(70);
            tableOrder.getColumnModel().getColumn(3).setMinWidth(50);
            tableOrder.getColumnModel().getColumn(3).setPreferredWidth(50);
            tableOrder.getColumnModel().getColumn(3).setMaxWidth(50);
            tableOrder.getColumnModel().getColumn(4).setMinWidth(60);
            tableOrder.getColumnModel().getColumn(4).setPreferredWidth(60);
            tableOrder.getColumnModel().getColumn(4).setMaxWidth(60);
            tableOrder.getColumnModel().getColumn(5).setMinWidth(70);
            tableOrder.getColumnModel().getColumn(5).setPreferredWidth(70);
            tableOrder.getColumnModel().getColumn(5).setMaxWidth(70);
            tableOrder.getColumnModel().getColumn(6).setMinWidth(75);
            tableOrder.getColumnModel().getColumn(6).setPreferredWidth(75);
            tableOrder.getColumnModel().getColumn(6).setMaxWidth(75);
            tableOrder.getColumnModel().getColumn(7).setMinWidth(80);
            tableOrder.getColumnModel().getColumn(7).setPreferredWidth(80);
            tableOrder.getColumnModel().getColumn(7).setMaxWidth(80);
            tableOrder.getColumnModel().getColumn(8).setMinWidth(70);
            tableOrder.getColumnModel().getColumn(8).setPreferredWidth(70);
            tableOrder.getColumnModel().getColumn(8).setMaxWidth(70);
        }

        lblFetchSts.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        lblFetchSts.setForeground(new java.awt.Color(255, 0, 0));

        lblUpdateSts.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(437, 437, 437)
                        .addComponent(lblUpdateSts))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(219, 219, 219)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblFetchSts))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack)
                    .addComponent(jLabel1))
                .addGap(22, 22, 22)
                .addComponent(lblFetchSts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUpdateSts)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        adminHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void tableOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableOrderMouseClicked
        int rows = tableOrder.getSelectedRow();
        int cols = tableOrder.getColumnCount();
        Object[] val = new Object[cols];
        for(int i = 0; i < cols; i++) {
            val[i]=tableOrder.getValueAt(rows, i);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tableOrderMouseClicked

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFetchSts;
    private javax.swing.JLabel lblUpdateSts;
    private javax.swing.JTable tableOrder;
    // End of variables declaration//GEN-END:variables
}
