/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package krishna_laundry;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author thakur-huni
 */
public class Order extends javax.swing.JFrame {

    /**
     * Creates new form Order
     */
    AdminHome adminHome;
    private boolean validUser;
    public Order(AdminHome obj) {
        initComponents();
        this.adminHome=obj;
        validUser=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnVerify = new javax.swing.JButton();
        lblSts = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbShirt = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbTshirt = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbPant = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbTowel = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cmbPajama = new javax.swing.JComboBox<>();
        cmbBedSheet = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Order");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel1.setText("Order Now");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/back.png"))); // NOI18N
        btnBack.setAlignmentX(0.3F);
        btnBack.setAlignmentY(5.5F);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Username");

        btnVerify.setText("Verify");
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyActionPerformed(evt);
            }
        });

        lblSts.setBackground(new java.awt.Color(246, 13, 13));
        lblSts.setText("Verify user first...");

        jLabel4.setText("Enter Shirt Quantity");

        cmbShirt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7" }));

        jLabel5.setText("Enter T-Shirt Quantity");

        cmbTshirt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7" }));

        jLabel6.setText("Enter Pant Quantity");

        cmbPant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", " " }));

        jLabel7.setText("Enter Towel  Quantity");

        cmbTowel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7" }));

        jLabel8.setText("Enter Pajama Quantity");

        cmbPajama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7" }));

        cmbBedSheet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7" }));

        jLabel9.setText("Enter Bed Sheet Quantity");

        btnOrder.setText("Order Now");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSts)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbShirt, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbTshirt, javax.swing.GroupLayout.Alignment.LEADING, 0, 209, Short.MAX_VALUE)
                            .addComponent(cmbPant, javax.swing.GroupLayout.Alignment.LEADING, 0, 209, Short.MAX_VALUE)
                            .addComponent(cmbTowel, javax.swing.GroupLayout.Alignment.LEADING, 0, 209, Short.MAX_VALUE)
                            .addComponent(cmbPajama, javax.swing.GroupLayout.Alignment.LEADING, 0, 209, Short.MAX_VALUE)
                            .addComponent(cmbBedSheet, javax.swing.GroupLayout.Alignment.LEADING, 0, 209, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnVerify)))
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(206, 206, 206)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVerify)))
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSts)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbShirt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbTshirt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbPant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbTowel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbPajama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbBedSheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        adminHome.setVisible(true);
        adminHome.setFlagOrder(true);
        this.dispose();

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
        lblSts.setText("Please wait for user verification...");
        if(isValidUser(txtUsername.getText()))
        {
            lblSts.setBackground(Color.black);
            this.validUser=true;
            lblSts.setText(txtUsername.getText()+" is a verified user.");
        }
        else
        {
            this.validUser=false;
            lblSts.setBackground(Color.red);
             lblSts.setText("Invalid user. Add this user first.");
        }
    }//GEN-LAST:event_btnVerifyActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
       if(validUser==true)
       {
             try
                {
                  
                          ConnectDB connectDB=new ConnectDB();
                          Connection con=(Connection) connectDB.connect();
                          PreparedStatement  ps= con.prepareStatement("INSERT INTO orders ( shirt, tshirt, pant, towel, pajama, bedsheet, date, username) VALUES (?,?, ?,?, ?, ?,CURRENT_TIMESTAMP,?);");
                          ps.setString(1, cmbShirt.getSelectedItem().toString());
                          ps.setString(2, cmbTshirt.getSelectedItem().toString());
                          ps.setString(3, cmbPant.getSelectedItem().toString());
                          ps.setString(4, cmbTowel.getSelectedItem().toString());
                          ps.setString(5, cmbPajama.getSelectedItem().toString());
                          ps.setString(6, cmbBedSheet.getSelectedItem().toString());
                          ps.setString(7,txtUsername.getText());
                          
                          int i=ps.executeUpdate();
                          if(i>0)
                          {
                              JOptionPane.showMessageDialog(this,"Order placed Successfully.");
                              txtUsername.setText(null);
                              cmbShirt.setSelectedIndex(0);
                              cmbTshirt.setSelectedIndex(0);
                              cmbPant.setSelectedIndex(0);
                              cmbTowel.setSelectedIndex(0);
                              cmbPajama.setSelectedIndex(0);
                              cmbBedSheet.setSelectedIndex(0);
                          }
                   
                }
                 catch(Exception e)
                    {
                        System.out.println("Error in Order.java : "+e);

                    }

           
           
           validUser=false;
           btnVerify.setBackground(Color.white);
           txtUsername.setBackground(Color.white);
           lblSts.setText("Verify user first.");
       }
       else
       {
           JOptionPane.showMessageDialog(this, "Please verify user first.");
           lblSts.setText("Please verify user first.");
           btnVerify.setBackground(Color.red);
           txtUsername.setBackground(Color.red);
       }
    }//GEN-LAST:event_btnOrderActionPerformed
 public boolean isValidUser(String username)
    {
            
            try
            {
                ConnectDB connectDB=new ConnectDB();
                Connection con=(Connection) connectDB.connect();
                 PreparedStatement  ps= con.prepareStatement("SELECT user_id FROM user_tb WHERE username=?");
                 ps.setString(1, username);
                 ResultSet rs=ps.executeQuery();
                 if(rs.next())
                 {
                   connectDB.disconnect();
                   return true;
                 }
                 else
                 {
                      connectDB.disconnect();
                     return false;
                 }
                
            }
            catch(Exception e)
            {
                System.out.println("Error Order.java : "+e);

            }
            return false;
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnVerify;
    private javax.swing.JComboBox<String> cmbBedSheet;
    private javax.swing.JComboBox<String> cmbPajama;
    private javax.swing.JComboBox<String> cmbPant;
    private javax.swing.JComboBox<String> cmbShirt;
    private javax.swing.JComboBox<String> cmbTowel;
    private javax.swing.JComboBox<String> cmbTshirt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSts;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
